### ISSUE TITLE
@conda-forge-admin, please remove bot automerge

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/willow-feedstock#22]

**Comment by darynwhite** [comment]
@conda-forge/core 

I don't know what has broken with this package and it has now moved beyond my ability to correct. Should I simply try restarting it fresh?

**Comment by ocefpaf** [comment]
Automerge was already removed. You can probably regenerate the [recipe with grayskull](https://github.com/conda-forge/staged-recipes#grayskull---recipe-generator-for-python-packages-on-pypi) and send a PR to refresh it. The meta.yaml syntax there is quite old.

**Comment by darynwhite** [comment]
Thanks! I'm used to seeing the bot respond... :octocat:
