### ISSUE TITLE
Invalid spec for the pillow-heif dependency

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/willow-feedstock#31]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The spec for the pillow-heif dependency is not valid
```
    - pillow-heif >=0.10.0,<1.0.0<py312|>=0.13.0,<1.0.0>=py312
```

The section on `<py312` or `>=py312` is not something that conda can make sense of. (I am unsure what the actual behavior is).

Note: this has been reported in https://github.com/conda-forge/admin-requests/issues/1087.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by darynwhite** [comment]
@SylvainCorlay thanks for raising this, I actually had a discussion about his here: https://github.com/conda/grayskull/issues/463#issuecomment-1835127160

When I was attempting to get the complete spec translated via `greyskull`. I thought I had updated it, but apparently it slipped through my tasks. I'll work on a fix.
